# Generated by Django 6.0.4 on 2026-04-22 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketprice',
            name='date',
        ),
        migrations.AddField(
            model_name='marketprice',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 22, 17, 18, 18, 437196, tzinfo=datetime.timezone.utc)),
        ),
    ]
