# Generated by Django 6.0.4 on 2026-04-22 17:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_remove_marketprice_date_marketprice_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketprice',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
