# Generated by Django 6.0.4 on 2026-04-23 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_alter_marketprice_date_created'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Farmers',
            new_name='Farmer',
        ),
    ]
